### ISSUE TITLE
Pypi version is not updated

### ISSUE THREAD

**Issue by libremente** [101t/bigbluebutton-api-python#18]
Hi @101t @ianespana,

I see that the latest version on pypi is the 0.0.11 (https://pypi.org/project/bigbluebutton-api-python/#history) and is not updated to the latest changes on master. Would it be possible to update the pypi package? May I help somehow? 

Thanks for the work!

**Comment by 101t** [comment]
Hi @libremente 
I don't own the pypi access, you may contact yunkai.wang@blindsidenetworks.com - @yunkaiwang to ask the update tags on repo.
best regards.
